name: Gitea Actions Demo

run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on:
  pull_request:
    branches:
      - master

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }} is testing out Gitea Actions 🚀"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "🔎 The name of the repo not including the owner is ${{ github.event.repository.name }}."
      - run: echo "🔎 Merge from ${{ github.head_ref }} into ${{ github.ref }}"
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
